config/routes.rb
Performanceci::Application.routes.draw do
  resources :build_endpoints

  resources :endpoints

  resources :builds do
    collection do
      get 'ongoing'
    end
  end

  resources :repositories do
    member do
      get 'summary'
      put 'build_latest'
    end
  end

  resources :results_overview

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  resources :users do
    member do
      get :local_login
    end
  end

  root 'results_overview#index'

  post '/webhooks/:user_id' => 'webhooks#hook'

end

app/models/build.rb
class Build < ActiveRecord::Base
  belongs_to :repository

  has_many :build_endpoints

  scope :ongoing, -> { where("build_status NOT IN(?)", %w(success failed warn error))}
  scope :newish, -> { where(["created_at > ?", 1.hour.ago])}

  BUILD_STATUSES = %w(pending building_container attacking_container success failed warn error)

  #TODO: Fill this out
  def provider
    if is_external?
      :external
    else
      :docker
    end
  end

  def is_external?
    repository.is_external?
  end

  def self.from_payload(payload)
    user = User.find(payload[:user_id])
    repository = user.repositories.find_by_github_id(payload['repository']['id'])
    Build.new(
      payload: JSON.generate(payload.to_hash),
      build_status: 'pending',
      before:  payload['before'],
      after: payload['after'],
      message: payload['message'],
      compare: payload['compare'],
      url: "https://github.com/#{repository.full_name}.git",
      repository: repository)
  end

  def run_build
    OrchestrationWorker.create(:build_id => id)
  end

  def mark_build_finished
    average = average_response_from_endpoints
    status = status_from_endpoints
    pct_change = percent_change_from_last_build(average)
    self.update_attributes!(
      build_status: status,
      average_response: average,
      percent_change: pct_change)
  end

  def mark_build_error(message = nil)
    self.update_attributes! build_status: :error, error_message: message
  end

  #TODO: prob need to add build endpoints here and then update them later
  #      in case some of them don't come back
  def add_endpoint(url, headers, attribs = {})
    # Add other options to where clause to make them unique endpoints
    endpoint = repository.endpoints.where({url: url}.merge(attribs)).first
    unless endpoint
      endpoint = Endpoint.create!({repository: repository, url: url,
        headers: JSON.generate(headers)}.merge(attribs))
    end
    endpoint
  end

  def update_status(status, pct_done)
    update_attributes! build_status:status,percent_done:pct_done
  end

  def configure_build(yaml_hash)
    (yaml_hash['endpoints'] || []).each do |e|
      add_endpoint(
        e['url'],
        (e['headers'] || {}).to_hash,
        max_response_time: e['max_response_time'],
        name: e['name'])
    end
  end

  def build_status_message
    Build.message_for_status(build_status)
  end

  def endpoint_benchmark(endpoint, average_response, score, data)
    #TODO: Move this to endpoint model with easier API
    build_endpoints.create!(
      response_time: average_response,
      score: score,
      data: JSON.generate(data),
      endpoint: endpoint,
      build: self)
  end

  def mark_endpoint_error(endpoint, error_message = "")
    build_endpoints.create!(
      response_time: 0,
      score: 0,
      data: [].to_json,
      endpoint: endpoint,
      #error_message: error_message,  #TODO
      status: :error,
      build: self)
  end

  def self.message_for_status(status)
    case (status || '').to_sym
    when :cloning
      "Cloning Code"
    when :preparing_target
      "Remote Target Preparations"
    when :pending
      "Waiting to Build"
    when :building_container
      "Building Docker Container"
    when :attacking_container
      "Benchmarking Container"
    when :saving_results
      "Saving Results"
    when :success
      "Success"
    when :failed
      "Build Failed: Endpoint exceeded maximum response time"
    when :warn
      "Build Warning: Endpoint exceeded target response time"
    when :error
      "Build Error"
    else
      "Unknown"
    end
  end

  private
    def average_response_from_endpoints
      avg = self.build_endpoints.where('response_time IS NOT NULL').average(:response_time)
      avg || 0
    end

    def status_from_endpoints
      statuses = self.build_endpoints.pluck(:status)
      sorted_statuses = statuses.sort_by do |status|
        ranking = {'error' => 0, 'failed' => 1, 'warn' => 2, 'success' => 3}
      end
      worst_status = sorted_statuses.first || :success
    end

    def percent_change_from_last_build(avg_resp)
      last_build = repository.builds.order('created_at DESC').where("id <> ?", id).first
      if avg_resp && last_build && last_build.average_response
        (avg_resp - last_build.average_response) / last_build.average_response
      else
        0
      end
    end

end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  before_filter :authenticate_user!

  before_action :set_build, only: [:show, :edit, :update, :destroy]

  # GET /builds
  # GET /builds.json
  def index
    @builds = Build.all
    respond_to do |format|
      format.html { render action: 'index' }
      format.json { render json: @builds.to_json}
    end
  end

  def ongoing
    @builds = Build.ongoing.newish.select(:id, :repository_id, :build_status, :percent_done)
    #TODO - move this to JSON serializer
    @builds = @builds.map do |build|
      attribs = build.attributes
      attribs[:status_message] = Build.message_for_status(attribs['build_status'])
      attribs
    end
    respond_to do |format|
      format.html { render action: 'index' }
      format.json { render json: @builds.to_json}
    end

  end


  # GET /builds/1
  # GET /builds/1.json
  def show
  end

  # GET /builds/new
  def new
    @build = Build.new
  end

  # GET /builds/1/edit
  def edit
  end

  # POST /builds
  # POST /builds.json
  def create
    @build = Build.new(build_params)

    respond_to do |format|
      if @build.save
        format.html { redirect_to @build, notice: 'Build was successfully created.' }
        format.json { render action: 'show', status: :created, location: @build }
      else
        format.html { render action: 'new' }
        format.json { render json: @build.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /builds/1
  # PATCH/PUT /builds/1.json
  def update
    respond_to do |format|
      if @build.update(build_params)
        format.html { redirect_to @build, notice: 'Build was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @build.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /builds/1
  # DELETE /builds/1.json
  def destroy
    @build.destroy
    respond_to do |format|
      format.html { redirect_to builds_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_build
      @build = Build.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def build_params
      params.require(:build).permit(:ref, :before, :after, :repository_id, :message, :url, :author, :payload)
    end
end

app/views/builds/_form.html.erb
<%= form_for(@build) do |f| %>
  <% if @build.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@build.errors.count, "error") %> prohibited this build from being saved:</h2>

      <ul>
      <% @build.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ref %><br>
    <%= f.text_field :ref %>
  </div>
  <div class="field">
    <%= f.label :before %><br>
    <%= f.text_field :before %>
  </div>
  <div class="field">
    <%= f.label :after %><br>
    <%= f.text_field :after %>
  </div>
  <div class="field">
    <%= f.label :repository_id %><br>
    <%= f.number_field :repository_id %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_area :url %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :payload %><br>
    <%= f.text_area :payload %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/builds/edit.html.erb
<h1>Editing build</h1>

<%= render 'form' %>

<%= link_to 'Show', @build %> |
<%= link_to 'Back', builds_path %>

app/views/builds/index.html.erb
<h1>Listing builds</h1>

<table>
  <thead>
    <tr>
      <th>Ref</th>
      <th>Before</th>
      <th>After</th>
      <th>Repository</th>
      <th>Message</th>
      <th>Url</th>
      <th>Author</th>
      <th>Payload</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @builds.each do |build| %>
      <tr>
        <td><%= build.ref %></td>
        <td><%= build.before %></td>
        <td><%= build.after %></td>
        <td><%= build.repository_id %></td>
        <td><%= build.message %></td>
        <td><%= build.url %></td>
        <td><%= build.author %></td>
        <td><%= build.payload %></td>
        <td><%= link_to 'Show', build %></td>
        <td><%= link_to 'Edit', edit_build_path(build) %></td>
        <td><%= link_to 'Destroy', build, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Build', new_build_path %>

app/views/builds/new.html.erb
<h1>New build</h1>

<%= render 'form' %>

<%= link_to 'Back', builds_path %>

app/views/builds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ref:</strong>
  <%= @build.ref %>
</p>

<p>
  <strong>Before:</strong>
  <%= @build.before %>
</p>

<p>
  <strong>After:</strong>
  <%= @build.after %>
</p>

<p>
  <strong>Repository:</strong>
  <%= @build.repository_id %>
</p>

<p>
  <strong>Message:</strong>
  <%= @build.message %>
</p>

<p>
  <strong>Url:</strong>
  <%= @build.url %>
</p>

<p>
  <strong>Author:</strong>
  <%= @build.author %>
</p>

<p>
  <strong>Payload:</strong>
  <%= @build.payload %>
</p>

<%= link_to 'Edit', edit_build_path(@build) %> |
<%= link_to 'Back', builds_path %>