config/routes.rb
Performanceci::Application.routes.draw do
  resources :build_endpoints

  resources :endpoints

  resources :builds do
    collection do
      get 'ongoing'
    end
  end

  resources :repositories do
    member do
      get 'summary'
      put 'build_latest'
    end
  end

  resources :results_overview

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  resources :users do
    member do
      get :local_login
    end
  end

  root 'results_overview#index'

  post '/webhooks/:user_id' => 'webhooks#hook'

end

app/models/endpoint.rb
class Endpoint < ActiveRecord::Base
  belongs_to :repository
  has_many :build_endpoints
  belongs_to :build
end

app/controllers/endpoints_controller.rb
class EndpointsController < ApplicationController
  before_action :set_endpoint, only: [:show, :edit, :update, :destroy]

  # GET /endpoints
  # GET /endpoints.json
  def index
    @endpoints = Endpoint.all
  end

  # GET /endpoints/1
  # GET /endpoints/1.json
  def show
  end

  # GET /endpoints/new
  def new
    @endpoint = Endpoint.new
  end

  # GET /endpoints/1/edit
  def edit
  end

  # POST /endpoints
  # POST /endpoints.json
  def create
    @endpoint = Endpoint.new(endpoint_params)

    respond_to do |format|
      if @endpoint.save
        format.html { redirect_to @endpoint, notice: 'Endpoint was successfully created.' }
        format.json { render action: 'show', status: :created, location: @endpoint }
      else
        format.html { render action: 'new' }
        format.json { render json: @endpoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /endpoints/1
  # PATCH/PUT /endpoints/1.json
  def update
    respond_to do |format|
      if @endpoint.update(endpoint_params)
        format.html { redirect_to @endpoint, notice: 'Endpoint was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @endpoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /endpoints/1
  # DELETE /endpoints/1.json
  def destroy
    @endpoint.destroy
    respond_to do |format|
      format.html { redirect_to endpoints_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_endpoint
      @endpoint = Endpoint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def endpoint_params
      params.require(:endpoint).permit(:name, :url, :headers, :repository_id, :benchmark_type)
    end
end

app/views/endpoints/_form.html.erb
<%= form_for(@endpoint) do |f| %>
  <% if @endpoint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@endpoint.errors.count, "error") %> prohibited this endpoint from being saved:</h2>

      <ul>
      <% @endpoint.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_area :url %>
  </div>
  <div class="field">
    <%= f.label :headers %><br>
    <%= f.text_area :headers %>
  </div>
  <div class="field">
    <%= f.label :repository_id %><br>
    <%= f.number_field :repository_id %>
  </div>
  <div class="field">
    <%= f.label :benchmark_type %><br>
    <%= f.text_field :benchmark_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/endpoints/edit.html.erb
<h1>Editing endpoint</h1>

<%= render 'form' %>

<%= link_to 'Show', @endpoint %> |
<%= link_to 'Back', endpoints_path %>

app/views/endpoints/index.html.erb
<h1>Listing endpoints</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Headers</th>
      <th>Repository</th>
      <th>Benchmark type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @endpoints.each do |endpoint| %>
      <tr>
        <td><%= endpoint.name %></td>
        <td><%= endpoint.url %></td>
        <td><%= endpoint.headers %></td>
        <td><%= endpoint.repository_id %></td>
        <td><%= endpoint.benchmark_type %></td>
        <td><%= link_to 'Show', endpoint %></td>
        <td><%= link_to 'Edit', edit_endpoint_path(endpoint) %></td>
        <td><%= link_to 'Destroy', endpoint, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Endpoint', new_endpoint_path %>

app/views/endpoints/new.html.erb
<h1>New endpoint</h1>

<%= render 'form' %>

<%= link_to 'Back', endpoints_path %>

app/views/endpoints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @endpoint.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @endpoint.url %>
</p>

<p>
  <strong>Headers:</strong>
  <%= @endpoint.headers %>
</p>

<p>
  <strong>Repository:</strong>
  <%= @endpoint.repository_id %>
</p>

<p>
  <strong>Benchmark type:</strong>
  <%= @endpoint.benchmark_type %>
</p>

<%= link_to 'Edit', edit_endpoint_path(@endpoint) %> |
<%= link_to 'Back', endpoints_path %>