config/routes.rb
Performanceci::Application.routes.draw do
  resources :build_endpoints

  resources :endpoints

  resources :builds do
    collection do
      get 'ongoing'
    end
  end

  resources :repositories do
    member do
      get 'summary'
      put 'build_latest'
    end
  end

  resources :results_overview

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  resources :users do
    member do
      get :local_login
    end
  end

  root 'results_overview#index'

  post '/webhooks/:user_id' => 'webhooks#hook'

end

app/controllers/results_overview_controller.rb
class ResultsOverviewController < ApplicationController
  before_filter :authenticate_user!

  before_action :set_repository, only: [:show, :edit, :update, :destroy]

  # GET /results_overview
  # GET /results_overview.json
  def index
    @repositories = Repository.all
    if params[:repository_id]
      @repository = Repository.find(params[:repository_id])
    else
      @repository = current_user.repositories.first
    end
    if @repository
      @build = @repository.last_build
    end
  end
end

app/helpers/results_overview_helper.rb
module ResultsOverviewHelper
  def format_percent(perc)
    perc ? (perc * 100).round(2) : ''
  end

  def format_response_time(num)
    num ? (num * 1000).round(0) : ''
  end

  def thumbs(change)
    if change
      if change < 0
        "<span style='color: green'><i class='fa fa-thumbs-up fa-fw'></i>#{change.abs} %</span>"
      else
        "<span style='color: red'><i class='fa fa-thumbs-down fa-fw'></i>#{change.abs} %</span>"
      end
    else
      ''
    end
  end

  def build_panel_css
    if @build
      case @build.build_status
      when 'success'
        "panel-success"
      when 'warn'
        "panel-warning"
      when 'error'
        "panel-danger"
      when 'failed'
        "panel-danger"
      else
        ''
      end
    else
      ""
    end
  end
end

app/views/results_overview/_external_modal.html.erb
<!-- Modal -->
<div class="modal fade" class='width: 900px;' id="externalModal" tabindex="-1" role="dialog" aria-labelledby="External Configuration">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Webhook Information</h4>
      </div>
      <div class="modal-body">
          <div>
              <h3>To trigger build: </h3>
                <pre style='width:800px'>curl -X PUT "http://<%= request.host_with_port%>/repositories/<%= @repository.id %>/build_latest?token=<%= @repository.build_token %>" -d ''</pre>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

      </div>
    </div>
  </div>
</div>

app/views/results_overview/index.html.erb
<div id="page-wrapper" ng-app="resultsOverviewControllers"<% if @repository %>ng-controller="BuildStatusCtrl" ng-init="init('/builds/ongoing.json', <%= @repository.id%>)" <% end %> >
    <div class="row">
        <div class="col-lg-10">
            <% if @repository %>
                <h2 class="page-header">Repository: <%= @repository.full_name%>
                    <% if @repository %>
                        <div class="pull-right">
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">Actions
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu pull-right" role="menu">
                                    <li><a href='#' ng-click="buildLatest(<%= @repository.id %>)">Build Latest</a></li>
                                    <% if @repository.is_external? %>
                                        <li><a href='' data-toggle="modal" data-target="#externalModal">Webook Information</a></li>
                                        <li><%= link_to 'Edit Repository', edit_repository_path(@repository) %></li>
                                    <% end %>
                                    <li><%= link_to 'Delete Repository', @repository, method: :delete, confirm: 'Are you sure?'%></li>
                                </ul>
                            </div>
                        </div>
                    <% end %>
                </h2>
            <% else %>
                <h2 class="page-header">No Repos</h2>
                <div class="row col-lg-4">
                    <%= link_to 'Add Repository', new_repository_path, :class => "btn btn-lg btn-success btn-block" %>
                </div>
            <% end %>
            <% if @build %>
                <div class="panel <%= build_panel_css%>">
                    <div class="panel-heading">
                        <p><%=@build.build_status_message %></p>
                    </div>
                    <div class="panel-body">
                        <% if @build.build_status == 'error' %>
                            <% if @build.error_message %>
                                <div style='font-size:11px;font-style:courier;'>Build Error: <%=@build.error_message.gsub("\n", "<br />").gsub('",', "<br />").html_safe if @build.error_message %></div>
                            <% end %>
                        <% else %>
                            <table>
                                <tr>
                                    <td style='width:180px'><h4>Average Response:</h4></td>
                                    <td style='width:130px'><h4><%= format_response_time @build.average_response %> ms</h4></td>
                                </tr>
                                <tr>
                                    <td><h4>Trend:</h4></td>
                                    <td><h4><%= thumbs(format_percent(@build.percent_change)).html_safe %></h4></td>
                                </tr>
                                <tr>
                                    <td><h4>Total Endpoints:</h4></td>
                                    <td><h4><%=@build.build_endpoints.count %></h4></td>
                                </tr>
                            </table>
                        <% end %>
                    </div>
                </div>
            <% elsif @repository %>
                <h3>Repository is ready to go! <br /><br /><% unless @repository.is_external? %>Push some new commits and we'll get going...<% end %></h3>
                <div class="row col-lg-4">
                  <br />
                  <a href='#' class="btn btn-lg btn-success btn-block" ng-click="buildLatest(<%= @repository.id %>)">Build Latest</a>
                </div>

            <% end %>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <% if @repository %>
    <div class="row">
        <div class="col-lg-10">
            <h3 class="page-header" ng-hide="!show_status">
            <div class="row col-lg-10">
                <p>
                    <strong>Build Status: {{build_status}}</strong>
                    <span class="pull-right text-muted">{{build_percent}}% Complete</span>
                </p>
                <div class="progress progress-striped active">
                    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: {{build_percent}}%">
                        <span class="sr-only">{{build_percent}}% Complete (success)</span>
                    </div>
                </div>
            </div>
            </h3>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div ng-controller="TestResultCtrl">
        <div ng-init="init('/repositories/<%= @repository.id%>/summary.json')"></div>

        <div class="row" ng-repeat="endpointdata in repodata">
            <div class="col-lg-10" >
                <div class="panel panel-default">
                    <div class="panel-heading" >
                        <i class="fa fa-bar-chart-o fa-fw"></i> Endpoint:{{endpointdata.endpoint.url}} response
                        <div class="pull-right">
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                                    Chart
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu pull-right" role="menu">
                                    <li><a href="#">Response time</a>
                                    </li>
                                    <li><a href="#">% Change</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                    	<linechart data="endpointdata"></linechart>
                    </div>
                    <!-- /.panel-body -->

                </div>
            </div>
            <!-- /.col-lg-10 -->
            <div class="col-lg-2">
                <!-- Start here -->
                <div class=" panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-plus-square fa-fw"></i>
                        Trend
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <ul class="chat">
                            <li class="left clearfix" style="border-bottom: 1px" ng-show="isTrendGood(endpointdata)">
                                <span class="chat-img pull-left">
                                    <i class="fa fa-thumbs-o-up fa-3x fa-fw" style="color:green"></i>
                                </span>
                                <div class="chat-body clearfix">
                                    <div class="header">
                                        <small class="pull-right text-muted">
                                            <i class="fa fa-clock-o fa-fw"></i> {{lastBuildMin(endpointdata)}}
                                        </small>
                                    </div>
                                </div>
                                <p>
                                Page or API endpoint response time is improving
                                </p>
                            </li>
                            <li class="right clearfix" style="border-bottom: 1px" ng-hide="isTrendGood(endpointdata)">
                                <span class="chat-img pull-right">
                                    <i class="fa fa-thumbs-o-down fa-3x fa-fw" style="color:red"></i>
                                </span>
                                <div class="chat-body clearfix">
                                    <div class="header">
                                        <small class="pull-left text-muted">
                                            <i class="fa fa-clock-o fa-fw"></i> {{lastBuildMin(endpointdata)}}
                                        </small>
                                    </div>
                                </div>
                                <p>
                                Page or API endpoint <strong>response time is degrading</strong>
                                </p>
                            </li>
                        </ul>
                    </div>
                    <!-- /.panel-body -->
                    <div class="panel-footer">
                    </div>
                    <!-- /.panel-footer -->
                </div>
                <!-- Stop here -->
            </div>
            <!-- /.col-lg-10 -->
        </div>
        <!-- Container div -->
    </div>
    <!-- /.row -->
    <% end %>
</div>
<% if @repository && @repository.is_external? %>
    <%= render 'external_modal' %>
<% end %>
<!-- /#page-wrapper -->
<!-- Page-Level Demo Scripts - Blank - Use for reference -->
<script src="/src/app/results-overview/controllers.js"></script>
<script src="/src/app/results-overview/services.js"></script>
<script src="/src/app/results-overview/directives.js"></script>