config/routes.rb
Performanceci::Application.routes.draw do
  resources :build_endpoints

  resources :endpoints

  resources :builds do
    collection do
      get 'ongoing'
    end
  end

  resources :repositories do
    member do
      get 'summary'
      put 'build_latest'
    end
  end

  resources :results_overview

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  resources :users do
    member do
      get :local_login
    end
  end

  root 'results_overview#index'

  post '/webhooks/:user_id' => 'webhooks#hook'

end

app/models/build_endpoint.rb
class BuildEndpoint < ActiveRecord::Base
  belongs_to :repository
  belongs_to :endpoint
  belongs_to :build

  STATUSES = %w(success failed warn error)

  before_create :set_status

  def set_status
    if status != :error
      if response_time
        if endpoint.max_response_time && response_time > endpoint.max_response_time
          self.status = :failed
        elsif endpoint.target_response_time && response_time > endpoint.target_response_time
          self.status = :warn
        else
          self.status = :success
        end
      else
        self.status = :error
      end
    end
  end
end

app/controllers/build_endpoints_controller.rb
class BuildEndpointsController < ApplicationController
  before_action :set_build_endpoint, only: [:show, :edit, :update, :destroy]

  # GET /build_endpoints
  # GET /build_endpoints.json
  def index
    @build_endpoints = BuildEndpoint.all
  end

  # GET /build_endpoints/1
  # GET /build_endpoints/1.json
  def show
  end

  # GET /build_endpoints/new
  def new
    @build_endpoint = BuildEndpoint.new
  end

  # GET /build_endpoints/1/edit
  def edit
  end

  # POST /build_endpoints
  # POST /build_endpoints.json
  def create
    @build_endpoint = BuildEndpoint.new(build_endpoint_params)

    respond_to do |format|
      if @build_endpoint.save
        format.html { redirect_to @build_endpoint, notice: 'Build endpoint was successfully created.' }
        format.json { render action: 'show', status: :created, location: @build_endpoint }
      else
        format.html { render action: 'new' }
        format.json { render json: @build_endpoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /build_endpoints/1
  # PATCH/PUT /build_endpoints/1.json
  def update
    respond_to do |format|
      if @build_endpoint.update(build_endpoint_params)
        format.html { redirect_to @build_endpoint, notice: 'Build endpoint was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @build_endpoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /build_endpoints/1
  # DELETE /build_endpoints/1.json
  def destroy
    @build_endpoint.destroy
    respond_to do |format|
      format.html { redirect_to build_endpoints_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_build_endpoint
      @build_endpoint = BuildEndpoint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def build_endpoint_params
      params.require(:build_endpoint).permit(:endpoint_id, :build_id, :data, :response_time, :score, :screenshot)
    end
end

app/views/build_endpoints/_form.html.erb
<%= form_for(@build_endpoint) do |f| %>
  <% if @build_endpoint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@build_endpoint.errors.count, "error") %> prohibited this build_endpoint from being saved:</h2>

      <ul>
      <% @build_endpoint.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :endpoint_id %><br>
    <%= f.number_field :endpoint_id %>
  </div>
  <div class="field">
    <%= f.label :build_id %><br>
    <%= f.number_field :build_id %>
  </div>
  <div class="field">
    <%= f.label :data %><br>
    <%= f.text_area :data %>
  </div>
  <div class="field">
    <%= f.label :response_time %><br>
    <%= f.text_field :response_time %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="field">
    <%= f.label :screenshot %><br>
    <%= f.text_area :screenshot %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/build_endpoints/edit.html.erb
<h1>Editing build_endpoint</h1>

<%= render 'form' %>

<%= link_to 'Show', @build_endpoint %> |
<%= link_to 'Back', build_endpoints_path %>

app/views/build_endpoints/index.html.erb
<h1>Listing build_endpoints</h1>

<table>
  <thead>
    <tr>
      <th>Endpoint</th>
      <th>Build</th>
      <th>Data</th>
      <th>Response time</th>
      <th>Score</th>
      <th>Screenshot</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @build_endpoints.each do |build_endpoint| %>
      <tr>
        <td><%= build_endpoint.endpoint_id %></td>
        <td><%= build_endpoint.build_id %></td>
        <td><%= build_endpoint.data %></td>
        <td><%= build_endpoint.response_time %></td>
        <td><%= build_endpoint.score %></td>
        <td><%= build_endpoint.screenshot %></td>
        <td><%= link_to 'Show', build_endpoint %></td>
        <td><%= link_to 'Edit', edit_build_endpoint_path(build_endpoint) %></td>
        <td><%= link_to 'Destroy', build_endpoint, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Build endpoint', new_build_endpoint_path %>

app/views/build_endpoints/new.html.erb
<h1>New build_endpoint</h1>

<%= render 'form' %>

<%= link_to 'Back', build_endpoints_path %>

app/views/build_endpoints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Endpoint:</strong>
  <%= @build_endpoint.endpoint_id %>
</p>

<p>
  <strong>Build:</strong>
  <%= @build_endpoint.build_id %>
</p>

<p>
  <strong>Data:</strong>
  <%= @build_endpoint.data %>
</p>

<p>
  <strong>Response time:</strong>
  <%= @build_endpoint.response_time %>
</p>

<p>
  <strong>Score:</strong>
  <%= @build_endpoint.score %>
</p>

<p>
  <strong>Screenshot:</strong>
  <%= @build_endpoint.screenshot %>
</p>

<%= link_to 'Edit', edit_build_endpoint_path(@build_endpoint) %> |
<%= link_to 'Back', build_endpoints_path %>